# Generated by Django 6.0.2 on 2026-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchhistory',
            name='extracted_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
